version: '3.8'

services:

  softdesignlivetest:
    build: .
    hostname: softdesignlivetest
    container_name: softdesignlivetest
    ports:
      - "8080:8080"
    depends_on:
      - broker
      - mongodb
      - redis

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.5
    hostname: zookeeper
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  broker:
    image: confluentinc/cp-kafka:7.9.0
    hostname: broker
    container_name: broker
    ports:
      - "9092:9092"
      - "9101:9101"
      - "19092:19092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:19092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  mongodb:
    image: mongo:8.0.6
    hostname: mongodb
    container_name: mongodb
    ports:
      - "27017:27017"
      - "8081:8081"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:7.4.2
    hostname: redis
    container_name: redis
    ports:
      - "6379:6379"

volumes:
  mongodb_data: