server:
  port: 8089

spring:
  application:
    name: softdesignlivetest

  data:
    mongodb:
      uri: mongodb://localhost:27017/livetest

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: livetest-java-spring-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: '*'

mongock:
  migration-scan-package: com.softdesign.livetest.migration.mongo